# File di configurazione mdtmain (key=value) — generato/aggiornato
# automaticamente da mdtmain (schermata Impostazioni, test continuato).
# Righe vuote o che iniziano con '#' vengono ignorate.

disableNet=1
minAlarmHour=10
maxAlarmHour=23
disableIMEI=0
disableAlarm=0
autoStart=1
testPin=
testSim=89390100002769055843
mdtcapProfile=reconnect-trap
schedulerProfile=Default
hdmi=1
doGPSFix=1
forceExtended=0
testSMS=0
fullScan=0
fullDiagLog=0
selfTest=0
alarmCheckPoint=1
disableSend=0
startDisclaim=1
dataDisclaim=1
autoConfig=1
